/**
 * This file is generated by sveltekit-api-fetch.
 * Do not edit it, as it will be overwritten.
 * Learn more here: https://github.com/Guibi1/sveltekit-api-fetch
 */

type ProjectAPI = {
    GET: {
        "/twilio": never;
        "/twilio/add-phone": never;
        "/twilio/answer": never;
        "/twilio/ask": never;
        "/twilio/login": never;
        "/twilio/register": never;
        "/twilio/status": never;
    };
    POST: {
        "/[language]/vault": { body: { id: number }; routeParams: { language: string } };
        "/login": { body: { phone: string; privateKey: string[] } };
        "/logout": never;
    };
    PUT: {
        "/[language]/vault": { body: { id: number; password: string }; routeParams: { language: string } };
    };
    DELETE: {
        "/[language]/vault": { body: { id: number }; routeParams: { language: string } };
    };
};
